todo/core/urls.py
from django.urls import path
from . import views

app_name = "Todo"

urlpatterns = [
    path('', views.index, name="index"),
    path("detalhes/<int:id>", views.detail, name="detail"),
    path("editar/<int:id>", views.edit, name="edit"),
    path("delete/<int:id>", views.delete, name="delete"),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

todo/core/models.py
from django.db import models

# Create your models here.
class ToDo(models.Model):
    title = models.CharField('Título', max_length=50, null=False)
    description = models.TextField('Descrição', blank=True, null=True)
    done = models.BooleanField("Finalizada", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Data de criação")

    class Meta:
        verbose_name_plural = "To Do"
        ordering = ['-created']

    def __str__(self):
        return self.title

todo/core/forms.py
from django import forms
from .models import ToDo

class ToDoForms(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ["title", "description", "done"]

todo/core/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import ToDo
from .forms import ToDoForms


def index(request):
    # Pegando todos as tarefas criadas
    lista_todos = ToDo.objects.all()

    # Paginação
    paginator = Paginator(lista_todos, 5)
    page = request.GET.get("page")
    todos = paginator.get_page(page)

    # Formulário para criar novas tarefas
    form = ToDoForms()
    if request.method == "POST":
        form = ToDoForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Todo:index")
        return render(request, 'core/index.html', context={"todos": todos, "form":form})

    return render(request, 'core/index.html', context={"todos": todos, "form":form})


def detail(request, id):
    todo = get_object_or_404(ToDo, pk=id)
    return render(request, "core/detail.html", context={"todo":todo})


def edit(request, id):
    todo = get_object_or_404(ToDo, pk=id)
    form = ToDoForms(instance=todo)

    if request.method == "POST":
        form = ToDoForms(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect("Todo:index")
        
        return render(request, 'core/edit.html', context={"form":form, "todo":todo})
        
    return render(request, 'core/edit.html', context={"form":form, "todo":todo})


def delete(request, id):
    todo = get_object_or_404(ToDo, pk=id)
    todo.delete()
    return redirect('Todo:index')

todo/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
</body>
</html>

todo/core/templates/core/detail.html
{% extends 'base.html' %}
{% block title %}{{ todo.title }}{% endblock %}

{% block content %}
<div class="col-md">
    <h1>{{todo.title}}</h1>
        {% if todo.done %}
        <p><strong>Status: </strong>Finalizada.</p>
        {% else %}
        <p><strong>Status: </strong>Não finalizada.</p>
        {% endif %}
    <p>
        <strong>Descrição:</strong>
        {{ todo.description }}
    </p>
    <form method="post"> 
        {% csrf_token %}
        <a class="add-link" href="{% url 'Todo:edit' todo.id %}"><div class="edit-div add-link">Editar</div></a>
    </form>
</div>
{% endblock %}

todo/core/templates/core/edit.html
{% extends 'base.html' %}
{% block title %}Editando{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Salvar alterações">
        <a class="add-link" href="{% url 'Todo:delete' todo.id %}"><div class="delete-div add-link">Apagar</div></a>

    </form>
{% endblock %}

todo/core/templates/core/index.html
{% extends 'base.html' %}
{% block title %}Lista de Tarefas{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md">
        <h1>Criar nova tarefa</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Criar Tarefa</button>
        </form>
    </div>
    <div class="col-sm">
        <h1>Lista de tarefas</h1>
        <tr>
            {% for todo in todos %}
                <td>{{ todo.title }}</td><br>
                <td>Finalizada: {% if todo.done %}<i class="bi bi-check2-circle"></i>{% else %}<i class="bi bi-x-circle"></i>{% endif %}
                <a id="space" href="{% url 'Todo:detail' todo.id %}">Detalhes</a></td>
                <br><hr>
            {% empty %}
                <p>Você ainda não criou nenhuma tarefa!</p>
            {% endfor %}
        </tr>


        <!--Div de Paginação -->
        <div class="div-pagination">
            {% if todos.has_previous %}
                <a href="?page={{ todos.previous_page_number }}"><i class="bi bi-arrow-left"></i></a>
            {% endif %}
            
            {{todos.number}} de {{ todos.paginator.num_pages}}

            {% if todos.has_next %}
                <a href="?page={{ todos.next_page_number }}"><i class="bi bi-arrow-right"></i></span></a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}